export const EVENTS = Object.freeze({
  PLAYER_DAMAGED: 'PLAYER_DAMAGED',
  PLAYER_DIED: 'PLAYER_DIED',
  ENEMY_DAMAGED: 'ENEMY_DAMAGED',
  ENEMY_DIED: 'ENEMY_DIED',
  ROOM_CLEARED: 'ROOM_CLEARED',
  BOON_SELECTED: 'BOON_SELECTED',
  BOSS_DEFEATED: 'BOSS_DEFEATED',
  GOLD_CHANGED: 'GOLD_CHANGED',
  SHARDS_CHANGED: 'SHARDS_CHANGED',
  HUD_REFRESH: 'HUD_REFRESH',
});

class EventBusImpl extends Phaser.Events.EventEmitter {}
export const EventBus = new EventBusImpl();
