import { GAME_CONFIG } from '../config/GameConfig.js';
import { GameManager } from '../core/GameManager.js';
import { EventBus, EVENTS } from '../core/EventBus.js';
import { InputManager } from '../core/InputManager.js';
import { AudioManager } from '../core/AudioManager.js';
import { Player } from '../player/Player.js';
import { makePlayerStats } from '../player/PlayerStats.js';
import { Enemy } from '../enemies/Enemy.js';
import { Boss } from '../enemies/Boss.js';
import { HUD } from '../ui/HUD.js';
import { OverlayMenu } from '../ui/OverlayMenu.js';
import { UpgradeSystem, ENTITIES } from '../systems/UpgradeSystem.js';
import { RoomManager } from '../systems/RoomManager.js';
import { LootSystem } from '../systems/LootSystem.js';
import { BIOMES } from '../systems/DungeonGenerator.js';

export class GameScene extends Phaser.Scene {
  constructor(){super('GameScene');}
  init(data){this.weaponId=data?.weapon||GameManager.ensureRun().weapon||'sword';}
  create(){
    OverlayMenu.clear();this.run=GameManager.ensureRun();this.run.weapon=this.weaponId;this.audio=new AudioManager(this);this.inputManager=new InputManager(this);this.enemies=this.physics.add.group({runChildUpdate:false});this.projectiles=this.physics.add.group();this.enemyProjectiles=this.physics.add.group();
    this.roomManager=new RoomManager(this);this.roomManager.setup(this.run.rooms);this.player=new Player(this,640,390,makePlayerStats(GameManager.save.progression.permanent),this.weaponId);this.hud=new HUD(this,this.player,this.run);this.bossActive=false;this.roomResolved=false;this.debugVisible=false;
    this.physics.world.setBounds(96,86,1088,550);this.cameras.main.setBounds(0,0,1280,720).startFollow(this.player,true,GAME_CONFIG.camera.lerpX,GAME_CONFIG.camera.lerpY).setDeadzone(GAME_CONFIG.camera.deadzoneW,GAME_CONFIG.camera.deadzoneH);
    this.physics.add.collider(this.player,this.enemyProjectiles,(p,proj)=>{p.takeDamage(proj.damage||15);proj.destroy();});this.physics.add.collider(this.enemies,this.enemies);this.physics.add.overlap(this.player,this.enemies,(p,e)=>{if(e.type==='charger'&&e.body.speed>250)p.takeDamage(e.damage);});
    this.input.on('pointerdown',p=>{if(p.button===2)p.event.preventDefault();});this.game.canvas.addEventListener('contextmenu',e=>e.preventDefault());
    this.bindEvents();this.startRoom();
    this.debugText=this.add.text(10,150,'',{fontSize:'12px',color:'#72ffa8',backgroundColor:'#050a08cc',padding:{x:8,y:8}}).setScrollFactor(0).setDepth(30000).setVisible(false);
  }
  bindEvents(){this._onEnemyDied=e=>{this.run.kills++;this.run.gold+=LootSystem.goldForEnemy(e);GameManager.save.statistics.enemiesDefeated++;EventBus.emit(EVENTS.GOLD_CHANGED);this.roomManager.checkClear();};this._onDamaged=(e,r)=>{this.run.damageDealt+=r.amount;this.player.ultimateCharge=Math.min(100,(this.player.ultimateCharge||0)+4);this.trySynergies(e,r);};this._onPlayerDied=()=>this.playerDeath();this._onRoomClear=()=>this.onRoomClear();this._onBoss=b=>{this.run.bosses++;GameManager.save.statistics.bossesDefeated++;GameManager.save.progression.soulShards+=LootSystem.shardsForBoss();this.bossActive=false;this.roomManager.checkClear();};EventBus.on(EVENTS.ENEMY_DIED,this._onEnemyDied);EventBus.on(EVENTS.ENEMY_DAMAGED,this._onDamaged);EventBus.on(EVENTS.PLAYER_DIED,this._onPlayerDied);EventBus.on(EVENTS.ROOM_CLEARED,this._onRoomClear);EventBus.on(EVENTS.BOSS_DEFEATED,this._onBoss);this.events.once('shutdown',()=>this.unbindEvents());}
  unbindEvents(){EventBus.off(EVENTS.ENEMY_DIED,this._onEnemyDied);EventBus.off(EVENTS.ENEMY_DAMAGED,this._onDamaged);EventBus.off(EVENTS.PLAYER_DIED,this._onPlayerDied);EventBus.off(EVENTS.ROOM_CLEARED,this._onRoomClear);EventBus.off(EVENTS.BOSS_DEFEATED,this._onBoss);this.hud?.destroy();}
  renderArena(biome){this.children.list.filter(o=>o.getData?.('arena')).forEach(o=>o.destroy());this.cameras.main.setBackgroundColor('#080b12');const floor=this.add.polygon(640,360,[0,110,170,0,1080,0,1280,110,1110,650,170,650],biome.floor).setData('arena',1).setDepth(-100);for(let i=0;i<22;i++){const x=Phaser.Math.Between(140,1140),y=Phaser.Math.Between(125,625);this.add.ellipse(x,y,Phaser.Math.Between(30,90),Phaser.Math.Between(8,22),biome.accent,.09).setData('arena',1).setDepth(-90);}const wall=this.add.graphics().setData('arena',1).setDepth(-80);wall.lineStyle(8,biome.accent,.28);wall.strokeRoundedRect(100,90,1080,540,30);this.add.text(640,105,biome.name.toUpperCase(),{fontSize:'14px',fontStyle:'bold',color:'#ffffffaa'}).setOrigin(.5).setData('arena',1).setDepth(50);}
  startRoom(){this.roomResolved=false;this.roomManager.cleared=false;this.player.setPosition(640,530);const local=this.run.rooms%3;const biomeIdx=Math.min(BIOMES.length-1,Math.floor(this.run.rooms/3));this.currentBiome=BIOMES[biomeIdx];this.renderArena(this.currentBiome);if(local===2){this.spawnBoss();}else{const count=3+Math.min(5,this.run.rooms);for(let i=0;i<count;i++){const types=['melee','ranged','charger'];this.spawnEnemy(types[i%types.length],1+this.run.rooms*.08);}if(this.run.rooms>0&&this.run.rooms%2===1)this.spawnEnemy('elite',1+this.run.rooms*.09);}}
  spawnEnemy(type='melee',difficulty=1){const p=this.randomSpawn();const e=new Enemy(this,p.x,p.y,type,difficulty);this.enemies.add(e);return e;}
  spawnBoss(){this.bossActive=true;const boss=new Boss(this,640,220,this.currentBiome.boss,1+this.run.rooms*.08);this.enemies.add(boss);this.cameras.main.zoomTo(GAME_CONFIG.camera.bossZoom,450);this.bossBarBack=this.add.rectangle(640,38,620,18,0x22263a).setScrollFactor(0).setDepth(22000);this.bossBar=this.add.rectangle(330,38,620,18,0xc67cff).setOrigin(0,.5).setScrollFactor(0).setDepth(22001);this.bossName=this.add.text(640,15,boss.name.toUpperCase(),{fontSize:'14px',fontStyle:'bold'}).setOrigin(.5).setScrollFactor(0).setDepth(22002);boss.hpBar.setVisible(false);boss.hpFill.setVisible(false);this.boss=boss;}
  randomSpawn(){let x,y;do{x=Phaser.Math.Between(160,1120);y=Phaser.Math.Between(140,430);}while(Phaser.Math.Distance.Between(x,y,this.player?.x||640,this.player?.y||530)<180);return{x,y};}
  update(time){if(!this.player||this.paused)return;this.player.update(time,this.inputManager,this.input.activePointer);this.enemies.getChildren().forEach(e=>e.update(time,this.player));this.projectiles.getChildren().forEach(p=>this.updateProjectile(p));this.enemyProjectiles.getChildren().forEach(p=>this.updateProjectile(p));if(this.boss?.active){this.bossBar.width=620*Math.max(0,this.boss.hp/this.boss.maxHP);}if(Phaser.Input.Keyboard.JustDown(this.inputManager.keys.pause))this.pauseMenu();if(Phaser.Input.Keyboard.JustDown(this.inputManager.keys.debug)){this.debugVisible=!this.debugVisible;this.debugText.setVisible(this.debugVisible);}if(this.debugVisible)this.debugText.setText(`FPS ${Math.round(this.game.loop.actualFps)}\nPlayer ${Math.round(this.player.x)}, ${Math.round(this.player.y)}\nRoom ${this.run.rooms}\nEnemies ${this.enemies.countActive(true)}\nWeapon ${this.player.weapon.id}\nBuild ${this.player.boons.map(b=>b.name).join(', ')||'-'}\nF4 God Mode • F5 +100 Gold • F6 Spawn Boss`);this.debugKeys();this.player.setDepth(this.player.y);}
  debugKeys(){if(!GAME_CONFIG.debug)return;this.f4||=this.input.keyboard.addKey('F4');this.f5||=this.input.keyboard.addKey('F5');this.f6||=this.input.keyboard.addKey('F6');if(Phaser.Input.Keyboard.JustDown(this.f4)){this.player.maxHP=99999;this.player.hp=99999;EventBus.emit(EVENTS.HUD_REFRESH);}if(Phaser.Input.Keyboard.JustDown(this.f5)){this.run.gold+=100;EventBus.emit(EVENTS.GOLD_CHANGED);}if(Phaser.Input.Keyboard.JustDown(this.f6)&&!this.bossActive)this.spawnBoss();}
  updateProjectile(p){if(!p.active)return;if(p.x<70||p.x>1210||p.y<60||p.y>660)p.destroy();}
  fireProjectile(owner,pointer,damage,element,forcedAngle=null){const world=this.cameras.main.getWorldPoint(pointer.x,pointer.y);const ang=forcedAngle??Phaser.Math.Angle.Between(owner.x,owner.y,world.x,world.y);const p=this.physics.add.image(owner.x,owner.y,'projectile').setTint(0x8fe7ff).setDepth(5000);p.damage=damage;p.element=element;p.body.setVelocity(Math.cos(ang)*620,Math.sin(ang)*620);this.projectiles.add(p);this.physics.add.overlap(p,this.enemies,(proj,e)=>{if(!proj.active||e.dead)return;e.receiveHit(proj.damage,proj.element,90,ang,false);proj.destroy();});}
  enemyProjectile(enemy,player,damage){const ang=Phaser.Math.Angle.Between(enemy.x,enemy.y,player.x,player.y);const p=this.physics.add.image(enemy.x,enemy.y,'projectile').setTint(0xff6b7d);p.damage=damage;p.body.setVelocity(Math.cos(ang)*250,Math.sin(ang)*250);this.enemyProjectiles.add(p);}
  meleeArc(owner,angle,range,arc,damage,element,strong=false){const g=this.add.graphics().setDepth(8000);g.lineStyle(strong?10:6,strong?0xffd77c:0xb8f1ff,.7);g.beginPath();g.arc(owner.x,owner.y,range,angle-arc/2,angle+arc/2,false);g.strokePath();this.tweens.add({targets:g,alpha:0,duration:120,onComplete:()=>g.destroy()});this.enemies.getChildren().forEach(e=>{if(!e.active||e.dead)return;const d=Phaser.Math.Distance.Between(owner.x,owner.y,e.x,e.y);if(d>range+25)return;const a=Phaser.Math.Angle.Between(owner.x,owner.y,e.x,e.y);if(Math.abs(Phaser.Math.Angle.Wrap(a-angle))<=arc/2+.18)e.receiveHit(damage,element,strong?180:95,angle,strong);});}
  radialDamage(x,y,radius,damage,element,strong=false){const ring=this.add.circle(x,y,radius,ENTITIES.AURELIA.tint,.12).setStrokeStyle(3,0xffffff,.35).setDepth(7000);this.tweens.add({targets:ring,scale:1.12,alpha:0,duration:220,onComplete:()=>ring.destroy()});this.enemies.getChildren().forEach(e=>{if(e.active&&!e.dead&&Phaser.Math.Distance.Between(x,y,e.x,e.y)<=radius)e.receiveHit(damage,element,strong?150:80,Phaser.Math.Angle.Between(x,y,e.x,e.y),strong);});}
  onHitFeedback(x,y,strong){this.audio.hit(strong);this.fxBurst(x,y,strong?0xffdd88:0xc8f3ff);if(GAME_CONFIG.accessibility.screenShake)this.cameras.main.shake(strong?75:35,strong?.006:.002);if(strong){this.physics.world.pause();this.time.delayedCall(55,()=>this.physics.world.resume());}}
  fxBurst(x,y,color){for(let i=0;i<10;i++){const p=this.add.circle(x,y,Phaser.Math.Between(2,5),color,.9).setDepth(9000);const a=Math.random()*Math.PI*2,d=Phaser.Math.Between(20,65);this.tweens.add({targets:p,x:x+Math.cos(a)*d,y:y+Math.sin(a)*d,alpha:0,scale:.2,duration:Phaser.Math.Between(180,360),onComplete:()=>p.destroy()});}}
  fxTrail(x,y,color){const c=this.add.circle(x,y,22,color,.24).setDepth(100);this.tweens.add({targets:c,alpha:0,scale:1.8,duration:240,onComplete:()=>c.destroy()});}
  trySynergies(enemy,result){if(Math.random()<this.player.chainLightningChance){const other=this.enemies.getChildren().find(e=>e.active&&!e.dead&&e!==enemy&&Phaser.Math.Distance.Between(e.x,e.y,enemy.x,enemy.y)<180);if(other){other.receiveHit(result.amount*.45,'Lightning',40,0,false);const l=this.add.line(0,0,enemy.x,enemy.y,other.x,other.y,0x8fe7ff,.8).setOrigin(0).setDepth(9000);this.tweens.add({targets:l,alpha:0,duration:100,onComplete:()=>l.destroy()});}}if(result.critical&&this.player.overcharge)this.radialDamage(enemy.x,enemy.y,80,result.amount*.35,'Lightning');}
  bossTelegraph(boss,player){const target={x:player.x,y:player.y};const tele=this.add.circle(target.x,target.y,80,0xff374f,.18).setStrokeStyle(4,0xff5a6f,.9).setDepth(6000);this.tweens.add({targets:tele,alpha:.65,duration:500,yoyo:true,onComplete:()=>{if(Phaser.Math.Distance.Between(target.x,target.y,this.player.x,this.player.y)<85)this.player.takeDamage(boss.damage*1.35);this.fxBurst(target.x,target.y,0xff596f);tele.destroy();}});}
  onRoomClear(){if(this.roomResolved)return;this.roomResolved=true;this.bossBarBack?.destroy();this.bossBar?.destroy();this.bossName?.destroy();this.boss=null;this.cameras.main.zoomTo(1,350);this.time.delayedCall(420,()=>this.rewardMenu());}
  rewardMenu(){const choices=UpgradeSystem.choices(3);OverlayMenu.show({title:'RECOMPENSA',subtitle:'Escolha uma bênção para esta run.',buttons:choices.map(b=>({label:`${b.rarity.name} • ${b.entity} — ${b.name} | ${b.desc}`,onClick:()=>{UpgradeSystem.apply(this.player,b);this.run.boons=this.player.boons;EventBus.emit(EVENTS.BOON_SELECTED,b);this.audio.reward();OverlayMenu.clear();this.nextRoom();}})).concat([{label:'CURAR 25% (ignorar bênção)',onClick:()=>{this.player.heal(this.player.maxHP*.25);OverlayMenu.clear();this.nextRoom();}}])});}
  nextRoom(){this.run.rooms++;GameManager.persist();if(this.run.rooms>=12){this.scene.start('GameOverScene',{won:true});return;}this.roomManager.setup(this.run.rooms);this.startRoom();this.hud.refresh();}
  playerDeath(){this.paused=true;this.physics.world.timeScale=.25;this.cameras.main.fade(700,10,10,18);this.time.delayedCall(750,()=>this.scene.start('GameOverScene',{won:false}));}
  pauseMenu(){if(this.paused)return;this.paused=true;this.physics.world.pause();OverlayMenu.show({title:'PAUSADO',subtitle:'A run está congelada.',buttons:[{label:'RESUME',onClick:()=>{OverlayMenu.clear();this.physics.world.resume();this.paused=false;}},{label:'CONTROLS',onClick:()=>OverlayMenu.show({title:'CONTROLES',subtitle:'WASD/Setas mover • Mouse mirar • LMB ataque • RMB especial • Q habilidade • R ultimate • SPACE dash • F3 debug',buttons:[{label:'VOLTAR',onClick:()=>{OverlayMenu.clear();this.paused=false;this.physics.world.resume();}}]})},{label:'RETURN TO MENU',danger:true,onClick:()=>{OverlayMenu.clear();GameManager.endRun({won:false});this.scene.start('MainMenuScene');}}]});}
}
