import { GameManager } from '../core/GameManager.js';
import { OverlayMenu } from '../ui/OverlayMenu.js';
import { NPCS, DialogueSystem } from '../systems/DialogueSystem.js';
import { WeaponFactory } from '../weapons/WeaponFactory.js';
export class HubScene extends Phaser.Scene {
  constructor(){super('HubScene');}
  create(){this.cameras.main.setBackgroundColor('#111528');const w=this.scale.width,h=this.scale.height;this.add.text(w/2,60,'O NEXO FRATURADO',{fontSize:'40px',fontStyle:'bold',color:'#a8ecff'}).setOrigin(.5);this.add.text(w/2,102,`Soul Shards: ${GameManager.save.progression.soulShards}`,{fontSize:'18px',color:'#ffd26f'}).setOrigin(.5);
    NPCS.forEach((npc,i)=>{const x=w/2+(i-1)*240,y=290;this.add.circle(x,y,60,Phaser.Display.Color.HexStringToColor(npc.color).color,.7);this.add.text(x,y+85,`${npc.name}\n${npc.role}`,{align:'center',fontSize:'16px'}).setOrigin(.5).setInteractive().on('pointerdown',()=>this.talk(npc));});
    const buttons=[['NOVA RUN',()=>{GameManager.newRun();this.scene.start('GameScene',{weapon:GameManager.save.progression.selectedWeapon||GameManager.save.progression.unlockedWeapons[0]||'sword'});}],[`MELHORIAS PERMANENTES`,()=>this.upgrades()],[`DESBLOQUEAR ARMAS`,()=>this.weapons()],['MENU PRINCIPAL',()=>this.scene.start('MainMenuScene')]];
    buttons.forEach(([label,fn],i)=>this.add.text(w/2,470+i*44,label,{fontSize:'18px',backgroundColor:'#1a2136',padding:{x:20,y:10}}).setOrigin(.5).setInteractive().on('pointerdown',fn));}
  talk(npc){const line=DialogueSystem.line(npc,GameManager.save);GameManager.persist();OverlayMenu.show({title:npc.name,subtitle:line,buttons:[{label:'FECHAR',onClick:()=>OverlayMenu.clear()}]});}
  upgrades(){const p=GameManager.save.progression,perm=p.permanent;const buy=(key,cost)=>{if(p.soulShards>=cost){p.soulShards-=cost;perm[key]=(perm[key]||0)+1;GameManager.persist();this.scene.restart();}};OverlayMenu.show({title:'PROGRESSÃO',subtitle:`Soul Shards: ${p.soulShards}`,buttons:[{label:`+5 HP (${10+perm.hp*5})`,onClick:()=>buy('hp',10+perm.hp*5)},{label:`+1% crítico (${14+perm.crit*7})`,onClick:()=>buy('crit',14+perm.crit*7)},{label:'FECHAR',onClick:()=>OverlayMenu.clear()}]});}
  weapons(){const p=GameManager.save.progression;const costs={spear:25,bow:35,gauntlets:45,scythe:60};const btns=WeaponFactory.ids().map(id=>({label:`${p.unlockedWeapons.includes(id)?'✓':`${costs[id]||0} shards`} — ${WeaponFactory.data()[id].name}`,onClick:()=>{if(p.unlockedWeapons.includes(id)){p.selectedWeapon=id;GameManager.persist();OverlayMenu.clear();this.scene.restart();}else if(p.soulShards>=(costs[id]||0)){p.soulShards-=costs[id]||0;p.unlockedWeapons.push(id);p.selectedWeapon=id;GameManager.persist();OverlayMenu.clear();this.scene.restart();}}}));btns.push({label:'FECHAR',onClick:()=>OverlayMenu.clear()});OverlayMenu.show({title:'ARSENAL',subtitle:`Soul Shards: ${p.soulShards}`,buttons:btns});}
}
