export const GAME_CONFIG = {
  gameName: 'SHATTERED REALMS',
  version: '0.1.0',
  width: 1280,
  height: 720,
  backgroundColor: '#0a0d16',
  playerBaseHP: 350,
  playerSpeed: 250,
  dashSpeed: 690,
  dashDuration: 140,
  dashCooldown: 430,
  criticalChance: 0.05,
  criticalMultiplier: 1.5,
  enemyDamageMultiplier: 1,
  enemyHealthMultiplier: 1,
  roomDifficultyMultiplier: 1,
  debug: true,
  camera: {
    lerpX: 0.085,
    lerpY: 0.085,
    deadzoneW: 110,
    deadzoneH: 70,
    zoom: 1,
    bossZoom: 0.9,
  },
  accessibility: {
    screenShake: 1,
    flashes: true,
    damageNumbers: true,
    highContrast: false,
    textScale: 1,
    showHitboxes: false,
  },
};
