export const GAME_CONFIG = {
  gameName: 'SHATTERED REALMS',
  version: '0.2.0-visual',
  width: 1280,
  height: 720,
  worldWidth: 1600,
  worldHeight: 900,
  backgroundColor: '#070912',
  playerBaseHP: 350,
  playerSpeed: 250,
  dashSpeed: 720,
  dashDuration: 145,
  dashCooldown: 430,
  criticalChance: 0.05,
  criticalMultiplier: 1.5,
  enemyDamageMultiplier: 1,
  enemyHealthMultiplier: 1,
  roomDifficultyMultiplier: 1,
  debug: true,
  camera: {
    cameraFollowSpeed: 0.085,
    cameraLookAhead: 54,
    cameraAimLookAhead: 26,
    cameraDeadzone: 24,
    cameraBaseZoom: 1.06,
    cameraCombatZoom: 0.98,
    cameraCrowdZoom: 0.93,
    cameraBossZoom: 0.90,
    cameraFinishZoom: 1.12,
    screenShakeMultiplier: 1,
  },
  effects: {
    particleQuality: 'HIGH',
    trailQuality: 'HIGH',
    flashIntensity: 1,
    hitStopMultiplier: 1,
    damageNumberScale: 1,
  },
  accessibility: {
    screenShake: 1,
    flashes: true,
    damageNumbers: true,
    highContrast: false,
    textScale: 1,
    showHitboxes: false,
    motionBlur: true,
    slowMotion: true,
  },
};
